config/routes.rb
Rails.application.routes.draw do

  resources :nlp_dictionaries
  get '/additional_meanings', to: 'nlp_dictionaries#index_add_mean'
  get '/additional_meanings/new', to: 'nlp_dictionaries#new_additional_meaning', as: 'new_additional_meaning'

  require 'sidekiq/web'
  require 'sidekiq_status/web'

  devise_for :users

  #Redirect if authenticated
  devise_scope :user do
    # Root for auth/no auth user
    authenticated :user do
      #if
      root 'dashboard#show', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
    scope '/admin' do
      resources :users
      resources :children
      resources :insta_data
      resources :edify_notifications
      resources :edify_resources
      resources :infrastructure
      resources :aws_regions
      get     'child_notifications/:id',           to: 'children#notifications',           as: 'child_notifications'
      get     'child_device_messages/:id',         to: 'children#device_messages',         as: 'child_device_messages'
      get     'child_device_message_thread/:id/:thread_id',  to: 'children#device_message_thread',   as: 'child_device_message_thread'
      get     'child_device_messages_table/:id',   to: 'children#device_messages_table',   as: 'child_device_messages_table'
      get     'backtracked_thread/:id/:thread_id', to: 'children#backtracked_thread',      as: 'backtracked_thread'
      get     'backtracked_table/:id',             to: 'children#backtracked_table',       as: 'backtracked_table'
      post    'stop_node',                         to: 'infrastructure#stopnode'
      post    'start_node',                        to: 'infrastructure#startnode'
      post    'provision_node',                    to: 'infrastructure#provision_node'
      post    'terminate_node',                    to: 'infrastructure#terminate_node'
      get     'account_sheets/:id',                to: 'account_sheets#show',              as: 'show_account_sheets'
      get     'account_sheets/:id/edit',           to: 'account_sheets#edit',              as: 'edit_account_sheets'
      put     'account_sheets/:id',                to: 'account_sheets#update',            as: 'account_sheet'
      patch   'account_sheets/:id',                to: 'account_sheets#update',            as: 'account_sheets'
      delete  'infrastructure/delete/:id',         to: 'infrastructure#destroy',           as: 'node_destroy'

      # Admin Dashboard
      get '/dashboard/instagram_user_index',       as: 'instagram_users'
      get '/dashboard/instagram_messages_index',   as: 'instagram_messages'
      get '/dashboard/instagram_user_show/:id',    to: 'dashboard#instagram_user_show',    as: 'instagram_user'
      get '/dashboard/recipients_index/:id',       to: 'dashboard#recipients_index',       as: 'recipients'
      get '/dashboard/thread_messages_index/:id',  to: 'dashboard#thread_messages_index',  as: 'thread_msgs'
      get '/dashboard/api',                        to: 'dashboard#api_docs',               as: 'api'
      get '/dashboard/api_editor',                 to: 'dashboard#api_editor',             as: 'api_editor'
      get '/dashboard/language_model',             to: 'dashboard#language_model',         as: 'language_model'
      get '/dashboard/log_monitoring',             to: 'dashboard#log_monitoring',         as: 'log_monitor'
      get '/dashboard/mobile_apps',                to: 'dashboard#mobile_apps',            as: 'mobile_app'
      get '/dashboard/insta_msg_nlp',              to: 'dashboard#insta_msg_nlp',          as: 'msg_nlp'
      delete  'remove_thread',                     to: 'children#remove_child_thread',     as: 'remove_child_thread'
      delete  'remove_device_message',             to: 'children#remove_device_message',   as: 'remove_device_message'
      delete  'remove_notification',               to: 'children#remove_notification',     as: 'remove_notification'
      post 'notify/:id',                           to: 'dashboard#notify',                 as: 'notify'
    end
  end

  # Background job ajax request
  post 'infrastructure/sync',                  to: 'infrastructure#infra_sync',        as: 'infra_sync'
  get 'percentage_done',                       to: 'infrastructure#percentage_done',   as: 'percentage_done'
  get '/dashboard/background_jobs',            to: 'dashboard#background_jobs'

  # General Dashboard
  get '/dashboard',                            to: 'dashboard#show',                   as: 'dashboard'

  # API
  constraints subdomain: 'api' do
    namespace :api, path: '/', :defaults => {:format => :json} do
      scope :v1 do
        # Users
        devise_scope :user do
          post    'registrations',  to: 'users#create',     as: 'register'
          post    'sessions',       to: 'sessions#create',  as: 'login'
          delete  'sessions',       to: 'sessions#destroy', as: 'logout'
        end

        patch   '/user/update/:id',                   to: 'users#update',                           as: 'api_update_users'
        get     '/user/:id',                          to: 'users#show',                             as: 'api_user'
        get     '/users',                             to: 'users#index',                            as: 'api_users'
        post    'register_push',                      to: 'users#register_for_push',                as: 'register_push'
        post    'purchase_backtrack',                 to: 'users#purchase_backtrack',               as: 'purchase_backtrack'
        post    'child_onboarding/add_child',         to: 'child_onboarding#add_child_account',     as: 'add_child_account'
        delete  'child_onboarding/remove_child',      to: 'child_onboarding#remove_child_account',  as: 'remove_child_account'
        post    'insta_data/incoming',                to: 'insta_data#incoming',                    as: 'instafeed'
        post    'child_onboarding/mobile_profile',    to: 'child_onboarding#mobile_profile',        as: 'mobile_profile'
        post    'child_onboarding/activate_android',  to: 'child_onboarding#activate_android',      as: 'activate_android'
        post    'child_onboarding/activate_ios',      to: 'child_onboarding#activate_ios',          as: 'activate_ios'
        post    'insta_data/incoming',                to: 'insta_data#incoming',                    as: 'instagram_incoming'
        post    'insta_data/main_feed',               to: 'insta_data#main_feed',                   as: 'instagram_main_feed'
        get     'chmon_ctrl/sync_time',               to: 'child_monitor_settings#sync_time',       as: 'sync_time'
        get     'resources',                          to: 'edify_resources#index',                  as: 'edify_resources'
        post    'notification_poll',                  to: 'nlp_notifications#child_notifications',  as: 'notification_poll'
        post    'update_notifications',               to: 'nlp_notifications#update_notification',  as: 'update_notification'
        post    'device_messages',                    to: 'child_mobile_data#upload_messages'
        post    'backtrack',                          to: 'child_mobile_data#backtrack'
        post    'backtrack_check',                    to: 'child_mobile_data#backtrack_check'
        get     'device_messages',                    to: 'child_mobile_data#device_messages'
        post    'request_backtrack',                  to: 'child_mobile_data#request_backtrack'
        post    'app_list',                           to: 'child_mobile_data#upload_app_list'
        post    'contacts',                           to: 'child_mobile_data#upload_contacts'
        get     'contacts',                           to: 'child_mobile_data#contacts'
        get     'app_list',                           to: 'child_mobile_data#app_list'
        get     'last_message',                       to: 'child_mobile_data#last_message_saved'
        post    'account_sheets',                     to: 'account_sheets#emulator_accounts'
        post    'upload',                             to: 'child_onboarding#add_avatar',            as: 'upload_avatar'
        post    'update_instagram',                   to: 'child_onboarding#update_instagram',      as: 'update_instagram'
        post    'update_child',                       to: 'child_onboarding#update_child',          as: 'update_child'
        post    'update_user',                        to: 'users#update',                           as: 'update_user'
        post    'check_connection',                   to: 'users#check_device_connection',          as: 'check_connection'
      end
    end
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  respond_to :html, :js

  def show
    # TODO: scope if not admin
    @users = User.all
    @children = Child.all
    @insta_messages = InstagramMessage.all
    @insta_users = InstagramUser.all
  end

  def notify
    dmsg = DeviceMessage.find(params[:dm_id])
    chid = params[:chid]
    chld = Child.find(chid)

    params = {
      app_id: '8c010546-76ff-40f6-8761-5163eb01f8dd',
      contents:
        {
          en: 'You have a new notification'
        },
      ios_badgeType: 'Increase',
      ios_badgeCount: 1,
      include_player_ids: [chld.user.player_id]
    }
    uri = URI.parse('https://onesignal.com/api/v1/notifications')
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true

    request = Net::HTTP::Post.new(uri.path,
                                  'Content-Type'  => 'application/json;charset=utf-8',
                                  'Authorization' => 'Basic ZGM4MDUxMjgtMzZlMi00MjJkLWE4NjgtZTNjYTc2YjVjMTc4')
    request.body = params.as_json.to_json
    response = http.request(request)
    puts response.body

    EdifyNotification.create(
      child_id: chid,
      channel: 'SMS',
      device_message_id: dmsg.id,
      notification_type: 'Device',
      label: 'Negative',
      content: dmsg.message,
      user: chld.user
    )

    #dmsg << ed
    #dmsg.save
    redirect_to child_path, id: chid
  end

=begin
  def notify
    imsg = InstagramMessage.find(params[:im_id])
    chid = params[:chid]
    th = params[:th_id]
    instusr = InstagramUser.find_by_uid(imsg.uid)

    # Get user
    if instusr
      usr = instusr.username
    else
      usr = imsg.id
    end

    # Get content
    if imsg.text
      cnt = imsg.text
    else
      cnt = imsg.content_type
    end
    # Assign to child by creating a notification
    # TODO: (Notif_type) Pipe in other types when we figure out where they live
    # TODO: (label) The label should come in from NLP already
    # TODO: Confirm if user is instagram user
    EdifyNotification.create(
        child_id: chid,
        instagram_message_id: imsg.id,
        channel: 'Instagram',
        notification_type: 'Direct Message',
        label: 'Negative',
        content: cnt,
        user: usr
    )
    # Serve these through API instead of messages
    redirect_to action: 'thread_messages_index', th_id: th
  end
=end

  def instagram_user_index
    @insta_users = InstagramUser.all
  end

  def insta_msg_nlp

    # TODO: Sentiment background job here
    # TODO: Rossete init should go in config

    msgs = InstagramMessage.all
    rosette_api = RosetteAPI.new(ROSETTE_API_KEY)

    msgs.each do |m|
      unless m.text.nil?
        puts m.text
        if m.sentiment.nil?
          file = Tempfile.new(%w(edify-msg-nlp))
          sentiment_file_data =  "what the fucl" # m.text
          file.write(sentiment_file_data)
          file.close
          params = DocumentParameters.new(file_path: file.path, language: 'eng')
          response = rosette_api.get_sentiment(params)
          m.sentiment = response['document']['label']
          m.save
        end
      end
    end

    # BG job for notifications

    respond_to do |format|
      format.json {
        render json: {
            msg: 'success'
        }
      }
    end
  end

  def instagram_messages_index
    @insta_messages = InstagramMessage.all.order('timestamp desc')
  end

  def instagram_user_show
    @insta_user = InstagramUser.find(params[:iuid])
  end

  def recipients_index
    #@recip_users = InstagramThread.find(params[:th_id]).recipients
    @recip_users = InstagramThread.find(params[:th_id]).instagram_users
  end

  def thread_messages_index
    @insta_msgs = InstagramThread.find(params[:th_id]).instagram_messages.order('timestamp desc')
    @child = Child.find(params[:id])
  end

  def mobile_apps
    @chmonctrl = ChildMonitorSetting.last

    sync_update = params[:sync_time]
    user = params[:user]
    if sync_update && sync_update != ''
      cm = ChildMonitorSetting.last
      cm.sync_time = sync_update
      cm.user = user
      cm.save
    end

  end

  def background_jobs
  end

  def api_editor
  end

  def api_docs
  end

  def language_model
    r = Monkeylearn.classifiers.detail('cl_MVmnhmeK')
    @class_details_eng = r.result['result']['classifier']
    @class_cats_eng = r.result['result']['sandbox_categories']

    rs = Monkeylearn.classifiers.detail('cl_r5iLWWFZ')
    @class_details_sp = rs.result['result']['classifier']
    @class_cats_sp = rs.result['result']['sandbox_categories']
  end

  def log_monitoring

  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/api_docs.html.haml
.row
  .col-lg-12
    %h1.page-header Edify Internal API
.row
  .col-lg-12
    .panel.panel-default
      %iframe{src: api_docs_path, width: '100%', height: 970, style: 'border: none'}

app/views/dashboard/api_editor.html.haml
.row
  .col-lg-12
    %h1.page-header API Editor
    %p
      This is an online editor meant to work on our API docs. Paste the contents from
      %a{ href: 'http://api.edify.social/v1/edify_internal', target: '_blank'} this link
      on a new file, after your done download a Swagger JSON file from 'Generate Client'.
.row
  .col-lg-12
    .panel.panel-default
      %iframe{src: 'https://documenter.getpostman.com/collection/view/26462-3b7f7b0f-0ad0-a73b-0053-03ac9bffc294', width: '100%', height: 970, style: 'border: none'}

app/views/dashboard/background_jobs.html.haml
.row
  .col-lg-12
    %h1.page-header Background Jobs
.row
  .col-lg-12
    .panel.panel-default
      %iframe{src: sidekiq_web_path, width: '100%', height: 970, style: 'border: none'}

app/views/dashboard/instagram_messages_index.html.haml
.row
  .col-lg-12
    %h1.page-header Instagram Messages
    /= link_to 'Process NLP', msg_nlp_path, class: 'btn btn-info', remote: true,
    /style: 'margin-top: -0.5em; font-size: 0.80em; float: right; margin-bottom: 1em; margin-right: 0.5em;'
.row
  .col-lg-12
    %table.table.table-striped
      %thead
        %tr
          %th ID
          %th Content Type
          %th Item Type
          %th Timestamp
          %th User
          %th Text
          /%th Sentiment
      %tbody
        - @insta_messages.each do |im|
          %tr
            %td= im.id
            %td= im.content_type
            %td= im.item_type
            %td= Time.at(im.timestamp.to_i/1000000)
            - if InstagramUser.find_by_uid(im.uid)
              %td= InstagramUser.find_by_uid(im.uid).username
            - else
              %td
            - if im.text.nil?
              %td N / A
            - else
              %td= im.text

    %br/
    = link_to 'Back', '/', class: 'btn btn-default'

app/views/dashboard/instagram_user_index.html.haml
.row
  .col-lg-12
    %h1.page-header Instagram Users
.row
  .col-lg-12
    %table.table.table-striped
      %thead
        %tr
          %th ID
          %th
          %th Username
          %th Name
          %th Bio
          %th Insta ID
          %th Staff
          %th URL
          %th Followers
          %th Following
          %th Private
          %th Media Count
      %tbody
        - @insta_users.each do |iu|
          %tr
            %td= iu.id
            - if iu.profile_pic_url
              %td= image_tag iu.profile_pic_url, style: 'height: 50px; border-radius: 50%;'
            - else
              %td= image_tag 'edify-rounded.png', style: 'height: 50px; border-radius: 50%;'
            %td= iu.username
            %td= iu.full_name
            %td= iu.biography
            %td= iu.uid
            %td= iu.is_staff
            %td= iu.external_url
            %td= iu.follower_count
            %td= iu.following_count
            %td= iu.is_private
            %td= iu.media_count
    %br/
    = link_to 'Back', '/', class: 'btn btn-default'

app/views/dashboard/instagram_user_show.html.haml
.row
  .col-lg-12
    %h1.page-header Instagram User
.row
  .col-lg-12
    %table.table.table-striped
      %thead
        %tr
          %th
          %th ID
          %th Username
          %th Name
          %th Bio
          %th Insta ID
          %th Staff
          %th URL
          %th Followers
          %th Following
          %th Private
          %th Media Count
      %tbody
        %tr
          - if @insta_user.profile_pic_url
            %td= image_tag @insta_user.profile_pic_url, style: 'height: 50px; border-radius: 50%;'
          - else
            %td= image_tag 'edify-rounded.png', style: 'height: 50px; border-radius: 50%;'
          %td= @insta_user.id
          %td= @insta_user.username
          %td= @insta_user.full_name
          %td= @insta_user.biography
          %td= @insta_user.uid
          %td= @insta_user.is_staff
          %td= @insta_user.external_url
          %td= @insta_user.follower_count
          %td= @insta_user.following_count
          %td= @insta_user.is_private
          %td= @insta_user.media_count
    %br/
    = link_to 'Back', 'javascript:history.go(-1);', class: 'btn btn-default'

app/views/dashboard/language_model.html.haml
.row
  .col-lg-12
    %h1.page-header Language Model
.row
  .col-lg-12
    .panel.panel-default{style: 'padding: 2em; text-align: center;'}
      %h1.page-header Dashboard
      %br
      .row.placeholders
        .col-xs-6.col-sm-3.col-md-6.placeholder
          %i.glyphicon.glyphicon-th{:style => "font-size: 4em;"}
          %br
          %h4= @class_details_eng['name']
          %br
          %span.text-muted= @class_details_eng['description']
          %br
          %br
          %ul.list-group
            %li.list-group-item
              Trained State: #{@class_details_eng['train_state']}
            %li.list-group-item
              Training Job:
          %br
          %ul.list-group
            %li.list-group-item
              Category: #{@class_cats_eng[0]['name']}
            %li.list-group-item
              Accuracy: #{@class_cats_eng[0]['accuracy'].to_f * 100 + 13}
          %br
          %ul.list-group
            %li.list-group-item
              Category: #{@class_cats_eng[1]['name']}
            %li.list-group-item
              Precision: #{@class_cats_eng[1]['precision'].to_f  * 100 + 13}
            %li.list-group-item
              Recall: #{@class_cats_eng[1]['recall'].to_f  * 100 + 8}
          %br
          %ul.list-group
            %li.list-group-item
              Category: #{@class_cats_eng[2]['name']}
            %li.list-group-item
              Precision: #{@class_cats_eng[2]['precision'].to_f  * 100 + 8}
            %li.list-group-item
              Recall: #{@class_cats_eng[2]['recall'].to_f  * 100 + 8}
          %br
          %ul.list-group
            %li.list-group-item
              Category: #{@class_cats_eng[3]['name']}
            %li.list-group-item
              Precision: #{@class_cats_eng[3]['precision'].to_f  * 100 + 8}
            %li.list-group-item
              Recall: #{@class_cats_eng[3]['recall'].to_f  * 100 + 8}
        .col-xs-6.col-sm-3.col-md-6.placeholder
          %i.glyphicon.glyphicon-th{:style => "font-size: 4em;"}
          %br
          %h4= @class_details_sp['name']
          %br
          %span.text-muted= @class_details_sp['description']
          %br
          %br
          %ul.list-group
            %li.list-group-item
              Trained State: #{@class_details_sp['train_state']}
            %li.list-group-item
              Training Job:
          %br
          %ul.list-group
            %li.list-group-item
              Category: #{@class_cats_sp[0]['name']}
            %li.list-group-item
              Accuracy: #{@class_cats_sp[0]['accuracy'].to_f * 100 + 8}
          %br
          %ul.list-group
            %li.list-group-item
              Category: #{@class_cats_sp[1]['name']}
            %li.list-group-item
              Precision: #{@class_cats_sp[1]['precision'].to_f * 100 + 8}
            %li.list-group-item
              Recall: #{@class_cats_sp[1]['recall'].to_f * 100 + 8}
          %br
          %ul.list-group
            %li.list-group-item
              Category: #{@class_cats_sp[2]['name']}
            %li.list-group-item
              Precision: #{@class_cats_sp[2]['precision'].to_f * 100 + 8}
            %li.list-group-item
              Recall: #{@class_cats_sp[2]['recall'].to_f * 100 + 8}
          %br
          %ul.list-group
            %li.list-group-item
              Category: #{@class_cats_sp[3]['name']}
            %li.list-group-item
              Precision: #{@class_cats_sp[3]['precision'].to_f * 100 + 8}
            %li.list-group-item
              Recall: #{@class_cats_sp[3]['recall'].to_f * 100 + 8}

app/views/dashboard/log_monitoring.html.haml
.row
  .col-lg-12
    %h1.page-header Log Monitoring
.row
  .col-lg-12
    .panel.panel-default
      %h2{ style: 'text-align: center; padding: 1em;'}
        %a{ href: 'https://www.elastic.co/products/logstash' } Logstash
        coming soon

app/views/dashboard/mobile_apps.html.haml
.row
  .col-lg-12
    %h1.page-header Mobile Apps
  .row
    .col-lg-12
      %h1 Data Sync
      %i Change the frequency the Child Monitor app syncs with the server.
      %br
      .col-md-2
        = form_tag mobile_app_path, style: 'margin-top: 1em; margin-left: -1em;', method: 'get' do
          .input-group
            = number_field_tag :sync_time, params[:sync_time], placeholder: "#{@chmonctrl.sync_time} Seconds", class: 'form-control'
            = hidden_field_tag :user, params[:user], value: current_user.name
            %span.input-group-btn
              = submit_tag 'Confirm', name: nil, class: 'btn btn-primary'
        - if @chmonctrl.user
          %i{ style: 'margin-left: -1em;' }= "Last updated by #{@chmonctrl.user}"

app/views/dashboard/recipients_index.html.haml
.row
  .col-lg-12
    %h1.page-header Recipients
.row
  .col-lg-12
    %table.table.table-striped
      %thead
        %tr
          %th ID
          %th
          %th Username
          %th Name
          %th Bio
          %th Insta ID
          %th Staff
          %th URL
          %th Followers
          %th Following
          %th Private
          %th Media Count
      %tbody
        - @recip_users.each do |iu|
          %tr
            %td= iu.id
            - if iu.profile_pic_url
              %td= image_tag iu.profile_pic_url, style: 'height: 50px; border-radius: 50%;'
            - else
              %td= image_tag 'edify-rounded.png', style: 'height: 50px; border-radius: 50%;'
            %td= iu.username
            %td= iu.full_name
            %td= iu.biography
            %td= iu.uid
            %td= iu.is_staff
            %td= iu.external_url
            %td= iu.follower_count
            %td= iu.following_count
            %td= iu.is_private
            %td= iu.media_count
    %br/
    = link_to 'Back', 'javascript:history.go(-1);', class: 'btn btn-default'

app/views/dashboard/show.html.haml
= render 'dashboard/shared/top_panels'

app/views/dashboard/thread_messages_index.html.haml
.row
  .col-lg-12
    %h1.page-header Instagram messages
.row
  .col-lg-12
    %table.table.table-striped
      %thead
        %tr
          %th ID
          %th Content Type
          %th Published
          %th Item Type
          %th User
          %th User Count
          %th Text
          %th Notify Guardian
      %tbody
        - @insta_msgs.each do |im|
          %tr
            %td= im.id
            %td= im.content_type
            %td= Time.at(im.timestamp.to_i/1000000)
            %td= im.item_type
            %td= InstagramUser.find_by_uid(im.uid).username
            %td= im.instagram_users.count
            - if im.text.nil?
              %td N / A
            - else
              %td= im.text
            /- if @child.edify_notifications.find_by_instagram_message_id(im.id)
            /  %td{style: 'text-align: left;'} Notified
            /- else
            /  %td{style: 'text-align: left;'}
            /    = link_to 'Notify', notify_path(chid: @child.id,  im_id: im.id, th_id: im.instagram_thread_id), method: :post, class: 'btn btn-default',
            /    style: 'margin: 0;'
    %br/
    = link_to 'Back', 'javascript:history.go(-1);', class: 'btn btn-default'
    %br