config/routes.rb
Rails.application.routes.draw do

  resources :nlp_dictionaries
  get '/additional_meanings', to: 'nlp_dictionaries#index_add_mean'
  get '/additional_meanings/new', to: 'nlp_dictionaries#new_additional_meaning', as: 'new_additional_meaning'

  require 'sidekiq/web'
  require 'sidekiq_status/web'

  devise_for :users

  #Redirect if authenticated
  devise_scope :user do
    # Root for auth/no auth user
    authenticated :user do
      #if
      root 'dashboard#show', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
    scope '/admin' do
      resources :users
      resources :children
      resources :insta_data
      resources :edify_notifications
      resources :edify_resources
      resources :infrastructure
      resources :aws_regions
      get     'child_notifications/:id',           to: 'children#notifications',           as: 'child_notifications'
      get     'child_device_messages/:id',         to: 'children#device_messages',         as: 'child_device_messages'
      get     'child_device_message_thread/:id/:thread_id',  to: 'children#device_message_thread',   as: 'child_device_message_thread'
      get     'child_device_messages_table/:id',   to: 'children#device_messages_table',   as: 'child_device_messages_table'
      get     'backtracked_thread/:id/:thread_id', to: 'children#backtracked_thread',      as: 'backtracked_thread'
      get     'backtracked_table/:id',             to: 'children#backtracked_table',       as: 'backtracked_table'
      post    'stop_node',                         to: 'infrastructure#stopnode'
      post    'start_node',                        to: 'infrastructure#startnode'
      post    'provision_node',                    to: 'infrastructure#provision_node'
      post    'terminate_node',                    to: 'infrastructure#terminate_node'
      get     'account_sheets/:id',                to: 'account_sheets#show',              as: 'show_account_sheets'
      get     'account_sheets/:id/edit',           to: 'account_sheets#edit',              as: 'edit_account_sheets'
      put     'account_sheets/:id',                to: 'account_sheets#update',            as: 'account_sheet'
      patch   'account_sheets/:id',                to: 'account_sheets#update',            as: 'account_sheets'
      delete  'infrastructure/delete/:id',         to: 'infrastructure#destroy',           as: 'node_destroy'

      # Admin Dashboard
      get '/dashboard/instagram_user_index',       as: 'instagram_users'
      get '/dashboard/instagram_messages_index',   as: 'instagram_messages'
      get '/dashboard/instagram_user_show/:id',    to: 'dashboard#instagram_user_show',    as: 'instagram_user'
      get '/dashboard/recipients_index/:id',       to: 'dashboard#recipients_index',       as: 'recipients'
      get '/dashboard/thread_messages_index/:id',  to: 'dashboard#thread_messages_index',  as: 'thread_msgs'
      get '/dashboard/api',                        to: 'dashboard#api_docs',               as: 'api'
      get '/dashboard/api_editor',                 to: 'dashboard#api_editor',             as: 'api_editor'
      get '/dashboard/language_model',             to: 'dashboard#language_model',         as: 'language_model'
      get '/dashboard/log_monitoring',             to: 'dashboard#log_monitoring',         as: 'log_monitor'
      get '/dashboard/mobile_apps',                to: 'dashboard#mobile_apps',            as: 'mobile_app'
      get '/dashboard/insta_msg_nlp',              to: 'dashboard#insta_msg_nlp',          as: 'msg_nlp'
      delete  'remove_thread',                     to: 'children#remove_child_thread',     as: 'remove_child_thread'
      delete  'remove_device_message',             to: 'children#remove_device_message',   as: 'remove_device_message'
      delete  'remove_notification',               to: 'children#remove_notification',     as: 'remove_notification'
      post 'notify/:id',                           to: 'dashboard#notify',                 as: 'notify'
    end
  end

  # Background job ajax request
  post 'infrastructure/sync',                  to: 'infrastructure#infra_sync',        as: 'infra_sync'
  get 'percentage_done',                       to: 'infrastructure#percentage_done',   as: 'percentage_done'
  get '/dashboard/background_jobs',            to: 'dashboard#background_jobs'

  # General Dashboard
  get '/dashboard',                            to: 'dashboard#show',                   as: 'dashboard'

  # API
  constraints subdomain: 'api' do
    namespace :api, path: '/', :defaults => {:format => :json} do
      scope :v1 do
        # Users
        devise_scope :user do
          post    'registrations',  to: 'users#create',     as: 'register'
          post    'sessions',       to: 'sessions#create',  as: 'login'
          delete  'sessions',       to: 'sessions#destroy', as: 'logout'
        end

        patch   '/user/update/:id',                   to: 'users#update',                           as: 'api_update_users'
        get     '/user/:id',                          to: 'users#show',                             as: 'api_user'
        get     '/users',                             to: 'users#index',                            as: 'api_users'
        post    'register_push',                      to: 'users#register_for_push',                as: 'register_push'
        post    'purchase_backtrack',                 to: 'users#purchase_backtrack',               as: 'purchase_backtrack'
        post    'child_onboarding/add_child',         to: 'child_onboarding#add_child_account',     as: 'add_child_account'
        delete  'child_onboarding/remove_child',      to: 'child_onboarding#remove_child_account',  as: 'remove_child_account'
        post    'insta_data/incoming',                to: 'insta_data#incoming',                    as: 'instafeed'
        post    'child_onboarding/mobile_profile',    to: 'child_onboarding#mobile_profile',        as: 'mobile_profile'
        post    'child_onboarding/activate_android',  to: 'child_onboarding#activate_android',      as: 'activate_android'
        post    'child_onboarding/activate_ios',      to: 'child_onboarding#activate_ios',          as: 'activate_ios'
        post    'insta_data/incoming',                to: 'insta_data#incoming',                    as: 'instagram_incoming'
        post    'insta_data/main_feed',               to: 'insta_data#main_feed',                   as: 'instagram_main_feed'
        get     'chmon_ctrl/sync_time',               to: 'child_monitor_settings#sync_time',       as: 'sync_time'
        get     'resources',                          to: 'edify_resources#index',                  as: 'edify_resources'
        post    'notification_poll',                  to: 'nlp_notifications#child_notifications',  as: 'notification_poll'
        post    'update_notifications',               to: 'nlp_notifications#update_notification',  as: 'update_notification'
        post    'device_messages',                    to: 'child_mobile_data#upload_messages'
        post    'backtrack',                          to: 'child_mobile_data#backtrack'
        post    'backtrack_check',                    to: 'child_mobile_data#backtrack_check'
        get     'device_messages',                    to: 'child_mobile_data#device_messages'
        post    'request_backtrack',                  to: 'child_mobile_data#request_backtrack'
        post    'app_list',                           to: 'child_mobile_data#upload_app_list'
        post    'contacts',                           to: 'child_mobile_data#upload_contacts'
        get     'contacts',                           to: 'child_mobile_data#contacts'
        get     'app_list',                           to: 'child_mobile_data#app_list'
        get     'last_message',                       to: 'child_mobile_data#last_message_saved'
        post    'account_sheets',                     to: 'account_sheets#emulator_accounts'
        post    'upload',                             to: 'child_onboarding#add_avatar',            as: 'upload_avatar'
        post    'update_instagram',                   to: 'child_onboarding#update_instagram',      as: 'update_instagram'
        post    'update_child',                       to: 'child_onboarding#update_child',          as: 'update_child'
        post    'update_user',                        to: 'users#update',                           as: 'update_user'
        post    'check_connection',                   to: 'users#check_device_connection',          as: 'check_connection'
      end
    end
  end

end

app/models/nlp_dictionary.rb
# == Schema Information
#
# Table name: nlp_dictionaries
#
#  id         :integer          not null, primary key
#  content    :text
#  label      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  weight     :decimal(, )
#

class NlpDictionary < ActiveRecord::Base
end

app/controllers/nlp_dictionaries_controller.rb
class NlpDictionariesController < ApplicationController
  before_action :set_nlp_dictionary, only: [:show, :edit, :update, :destroy]

  # GET /nlp_dictionaries
  # GET /nlp_dictionaries.json
  def index
    @nlp_dictionaries = NlpDictionary.all
  end

  # GET /nlp_dictionaries/1
  # GET /nlp_dictionaries/1.json
  def show
  end

  # GET /nlp_dictionaries/new
  def new
    @nlp_dictionary = NlpDictionary.new
  end

  def new_additional_meaning
    @nlp_dictionary = NlpDictionary.new
  end

  # GET /nlp_dictionaries/1/edit
  def edit
  end

  def index_add_mean
    @nlp_dictionaries = NlpDictionary.where('weight < ?', 100)
  end

  # POST /nlp_dictionaries
  # POST /nlp_dictionaries.json
  def create
    @nlp_dictionary = NlpDictionary.new(nlp_dictionary_params)

    respond_to do |format|
      if @nlp_dictionary.save
        format.html { redirect_to @nlp_dictionary, notice: 'Nlp dictionary was successfully created.' }
        format.json { render :show, status: :created, location: @nlp_dictionary }
      else
        format.html { render :new }
        format.json { render json: @nlp_dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nlp_dictionaries/1
  # PATCH/PUT /nlp_dictionaries/1.json
  def update
    respond_to do |format|
      if @nlp_dictionary.update(nlp_dictionary_params)
        format.html { redirect_to @nlp_dictionary, notice: 'Nlp dictionary was successfully updated.' }
        format.json { render :show, status: :ok, location: @nlp_dictionary }
      else
        format.html { render :edit }
        format.json { render json: @nlp_dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nlp_dictionaries/1
  # DELETE /nlp_dictionaries/1.json
  def destroy
    @nlp_dictionary.destroy
    respond_to do |format|
      format.html { redirect_to nlp_dictionaries_url, notice: 'Nlp dictionary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nlp_dictionary
      @nlp_dictionary = NlpDictionary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nlp_dictionary_params
      params.require(:nlp_dictionary).permit(:content, :label, :weight)
    end
end

app/helpers/nlp_dictionaries_helper.rb
module NlpDictionariesHelper
end

app/views/nlp_dictionaries/_form.html.haml
= simple_form_for(@nlp_dictionary) do |f|
  = f.error_notification

  .form-inputs
    = f.input :content
    = f.input :label
    = f.hidden_field :weight, value: 100

  %br
  %hr
  %br
  .form-actions
    = f.button :submit, 'Save', class: 'btn btn-success'

app/views/nlp_dictionaries/_form_add_mean.html.haml
= simple_form_for(@nlp_dictionary) do |f|
  = f.error_notification

  .form-inputs
    = f.input :content
    = f.input :label
    = f.input :weight

  %br
  %hr
  %br
  .form-actions
    = f.button :submit, 'Save', class: 'btn btn-success'

app/views/nlp_dictionaries/edit.html.haml
.row
  .container
    .col-md-5
      %h1.page-header NLP Dictionary
    .col-md-7
      = link_to 'Show', @nlp_dictionary, class: 'btn btn-primary top-btn', style: 'margin-left: 2em;'
      = link_to 'Back', nlp_dictionaries_path, class: 'btn btn-default top-btn'
  %br
.row
  .col-md-6.col-md-offset-3
    = render 'form'

app/views/nlp_dictionaries/index.html.haml
.row
  .col-md-12
    %h1.page-header NLP Dictionary
    %i The weight for each entry is 100%

%br
%br
.row
  .col-lg-12
    %table.table.table-striped
      %thead
        %tr
          %th Content
          %th Label
          %th
          %th
          %th

      %tbody
        - @nlp_dictionaries.each do |nlp_dictionary|
          %tr
            %td= nlp_dictionary.content
            %td= nlp_dictionary.label
            %td= link_to 'Show', nlp_dictionary
            %td= link_to 'Edit', edit_nlp_dictionary_path(nlp_dictionary)
            %td= link_to 'Destroy', nlp_dictionary, :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br
    %hr
    %br
    = link_to 'New dictionary entry', new_nlp_dictionary_path, class: 'btn btn-primary'

app/views/nlp_dictionaries/index_add_mean.html.haml
.row
  .col-md-12
    %h1.page-header Additional Meanings to Dictionary Entries

%br
%br
.row
  .col-lg-12
    %table.table.table-striped
      %thead
        %tr
          %th Content
          %th Label
          %th Weight
          %th
          %th
          %th

      %tbody
        - @nlp_dictionaries.each do |nlp_dictionary|
          %tr
            %td= nlp_dictionary.content
            %td= nlp_dictionary.label
            %td= nlp_dictionary.weight
            %td= link_to 'Show', nlp_dictionary
            %td= link_to 'Edit', edit_nlp_dictionary_path(nlp_dictionary)
            %td= link_to 'Destroy', nlp_dictionary, :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br
    %hr
    %br
    = link_to 'New Additional Meaning', new_additional_meaning_path, class: 'btn btn-primary'

app/views/nlp_dictionaries/new.html.haml
.row
  .container
    .col-md-5
      %h1.page-header New Dictionary Entry
    .col-md-7
      = link_to 'Back', nlp_dictionaries_path, class: 'btn btn-default top-btn'
  %br
.row
  .col-md-6.col-md-offset-3
    = render 'form'

app/views/nlp_dictionaries/new_additional_meaning.html.haml
.row
  .container
    .col-md-5
      %h1.page-header New Additional Meaning
    .col-md-7
      = link_to 'Back', additional_meanings_path, class: 'btn btn-default top-btn'
  %br
.row
  .col-md-6.col-md-offset-3
    = render 'form_add_mean'

app/views/nlp_dictionaries/show.html.haml
.row
  .col-md-12
    %h1.page-header NLP Dictionary

.row
  .col-lg-12
    %table.table.table-striped
      %thead
        %tr
          %th Attribute
          %th Value
      %tbody
        %tr
          %td ID
          %td= @nlp_dictionary.id
        %tr
          %td Content
          %td= @nlp_dictionary.content
        %tr
          %td Label:
          %td= @nlp_dictionary.label

= link_to 'Edit', edit_nlp_dictionary_path(@nlp_dictionary), class: 'btn btn-primary pull-right'
= link_to 'Back', nlp_dictionaries_path, class: 'btn btn-default'