config/routes.rb
Rails.application.routes.draw do

  resources :nlp_dictionaries
  get '/additional_meanings', to: 'nlp_dictionaries#index_add_mean'
  get '/additional_meanings/new', to: 'nlp_dictionaries#new_additional_meaning', as: 'new_additional_meaning'

  require 'sidekiq/web'
  require 'sidekiq_status/web'

  devise_for :users

  #Redirect if authenticated
  devise_scope :user do
    # Root for auth/no auth user
    authenticated :user do
      #if
      root 'dashboard#show', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
    scope '/admin' do
      resources :users
      resources :children
      resources :insta_data
      resources :edify_notifications
      resources :edify_resources
      resources :infrastructure
      resources :aws_regions
      get     'child_notifications/:id',           to: 'children#notifications',           as: 'child_notifications'
      get     'child_device_messages/:id',         to: 'children#device_messages',         as: 'child_device_messages'
      get     'child_device_message_thread/:id/:thread_id',  to: 'children#device_message_thread',   as: 'child_device_message_thread'
      get     'child_device_messages_table/:id',   to: 'children#device_messages_table',   as: 'child_device_messages_table'
      get     'backtracked_thread/:id/:thread_id', to: 'children#backtracked_thread',      as: 'backtracked_thread'
      get     'backtracked_table/:id',             to: 'children#backtracked_table',       as: 'backtracked_table'
      post    'stop_node',                         to: 'infrastructure#stopnode'
      post    'start_node',                        to: 'infrastructure#startnode'
      post    'provision_node',                    to: 'infrastructure#provision_node'
      post    'terminate_node',                    to: 'infrastructure#terminate_node'
      get     'account_sheets/:id',                to: 'account_sheets#show',              as: 'show_account_sheets'
      get     'account_sheets/:id/edit',           to: 'account_sheets#edit',              as: 'edit_account_sheets'
      put     'account_sheets/:id',                to: 'account_sheets#update',            as: 'account_sheet'
      patch   'account_sheets/:id',                to: 'account_sheets#update',            as: 'account_sheets'
      delete  'infrastructure/delete/:id',         to: 'infrastructure#destroy',           as: 'node_destroy'

      # Admin Dashboard
      get '/dashboard/instagram_user_index',       as: 'instagram_users'
      get '/dashboard/instagram_messages_index',   as: 'instagram_messages'
      get '/dashboard/instagram_user_show/:id',    to: 'dashboard#instagram_user_show',    as: 'instagram_user'
      get '/dashboard/recipients_index/:id',       to: 'dashboard#recipients_index',       as: 'recipients'
      get '/dashboard/thread_messages_index/:id',  to: 'dashboard#thread_messages_index',  as: 'thread_msgs'
      get '/dashboard/api',                        to: 'dashboard#api_docs',               as: 'api'
      get '/dashboard/api_editor',                 to: 'dashboard#api_editor',             as: 'api_editor'
      get '/dashboard/language_model',             to: 'dashboard#language_model',         as: 'language_model'
      get '/dashboard/log_monitoring',             to: 'dashboard#log_monitoring',         as: 'log_monitor'
      get '/dashboard/mobile_apps',                to: 'dashboard#mobile_apps',            as: 'mobile_app'
      get '/dashboard/insta_msg_nlp',              to: 'dashboard#insta_msg_nlp',          as: 'msg_nlp'
      delete  'remove_thread',                     to: 'children#remove_child_thread',     as: 'remove_child_thread'
      delete  'remove_device_message',             to: 'children#remove_device_message',   as: 'remove_device_message'
      delete  'remove_notification',               to: 'children#remove_notification',     as: 'remove_notification'
      post 'notify/:id',                           to: 'dashboard#notify',                 as: 'notify'
    end
  end

  # Background job ajax request
  post 'infrastructure/sync',                  to: 'infrastructure#infra_sync',        as: 'infra_sync'
  get 'percentage_done',                       to: 'infrastructure#percentage_done',   as: 'percentage_done'
  get '/dashboard/background_jobs',            to: 'dashboard#background_jobs'

  # General Dashboard
  get '/dashboard',                            to: 'dashboard#show',                   as: 'dashboard'

  # API
  constraints subdomain: 'api' do
    namespace :api, path: '/', :defaults => {:format => :json} do
      scope :v1 do
        # Users
        devise_scope :user do
          post    'registrations',  to: 'users#create',     as: 'register'
          post    'sessions',       to: 'sessions#create',  as: 'login'
          delete  'sessions',       to: 'sessions#destroy', as: 'logout'
        end

        patch   '/user/update/:id',                   to: 'users#update',                           as: 'api_update_users'
        get     '/user/:id',                          to: 'users#show',                             as: 'api_user'
        get     '/users',                             to: 'users#index',                            as: 'api_users'
        post    'register_push',                      to: 'users#register_for_push',                as: 'register_push'
        post    'purchase_backtrack',                 to: 'users#purchase_backtrack',               as: 'purchase_backtrack'
        post    'child_onboarding/add_child',         to: 'child_onboarding#add_child_account',     as: 'add_child_account'
        delete  'child_onboarding/remove_child',      to: 'child_onboarding#remove_child_account',  as: 'remove_child_account'
        post    'insta_data/incoming',                to: 'insta_data#incoming',                    as: 'instafeed'
        post    'child_onboarding/mobile_profile',    to: 'child_onboarding#mobile_profile',        as: 'mobile_profile'
        post    'child_onboarding/activate_android',  to: 'child_onboarding#activate_android',      as: 'activate_android'
        post    'child_onboarding/activate_ios',      to: 'child_onboarding#activate_ios',          as: 'activate_ios'
        post    'insta_data/incoming',                to: 'insta_data#incoming',                    as: 'instagram_incoming'
        post    'insta_data/main_feed',               to: 'insta_data#main_feed',                   as: 'instagram_main_feed'
        get     'chmon_ctrl/sync_time',               to: 'child_monitor_settings#sync_time',       as: 'sync_time'
        get     'resources',                          to: 'edify_resources#index',                  as: 'edify_resources'
        post    'notification_poll',                  to: 'nlp_notifications#child_notifications',  as: 'notification_poll'
        post    'update_notifications',               to: 'nlp_notifications#update_notification',  as: 'update_notification'
        post    'device_messages',                    to: 'child_mobile_data#upload_messages'
        post    'backtrack',                          to: 'child_mobile_data#backtrack'
        post    'backtrack_check',                    to: 'child_mobile_data#backtrack_check'
        get     'device_messages',                    to: 'child_mobile_data#device_messages'
        post    'request_backtrack',                  to: 'child_mobile_data#request_backtrack'
        post    'app_list',                           to: 'child_mobile_data#upload_app_list'
        post    'contacts',                           to: 'child_mobile_data#upload_contacts'
        get     'contacts',                           to: 'child_mobile_data#contacts'
        get     'app_list',                           to: 'child_mobile_data#app_list'
        get     'last_message',                       to: 'child_mobile_data#last_message_saved'
        post    'account_sheets',                     to: 'account_sheets#emulator_accounts'
        post    'upload',                             to: 'child_onboarding#add_avatar',            as: 'upload_avatar'
        post    'update_instagram',                   to: 'child_onboarding#update_instagram',      as: 'update_instagram'
        post    'update_child',                       to: 'child_onboarding#update_child',          as: 'update_child'
        post    'update_user',                        to: 'users#update',                           as: 'update_user'
        post    'check_connection',                   to: 'users#check_device_connection',          as: 'check_connection'
      end
    end
  end

end

app/controllers/infrastructure_controller.rb
class InfrastructureController < ApplicationController
  before_action :set_node, only: [:show, :destroy]

  DEBUG_INDEX = false

  def index
    @debug = DEBUG_INDEX
    @nodes = Node.all
    @aws_regions = AwsRegion.where(active: true)
  end

  def show
    node = Node.find(params[:id])
    if node.aws_id == 'i-eaded85f'
      @staging = Node.find_by_aws_id('i-eaded85f')
    else
      @staging = nil
    end
  end

  def terminate_node
    aws_inst = params[:inst_id]
    TerminateInstanceWorker.perform_async(aws_inst)

    redirect_to(infrastructure_index_path, notice: 'Instance termination scheduled.')
  end

  def provision_node
    # Provision with AWS
    ProvisionInstanceWorker.perform_async(0)

    if Rails.env.development?
      redirect_to(infrastructure_index_path,
                  notice: 'Instance provioning scheduled. Launched at us-east-2, make sure you have it in your aws regions.'
      )
    else
      redirect_to(infrastructure_index_path,
                  notice: 'Instance provioning scheduled. Launched at us-west-2, make sure you have it in your aws regions.'
      )
    end
  end

  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to infrastructure_index_path, notice: 'Node record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def infra_sync
    @job_id = InfraUpdateWorker.perform_async
  end

  def percentage_done
    job_id = params[:job_id]
    # Using the sidekiq_status gem to query the background job for progress information.
    container = SidekiqStatus::Container.load(job_id)
    @pct_complete = container.pct_complete

    respond_to do |format|
      format.json {
        render json: {
            percentage_done: @pct_complete
        }
      }
    end
  end

  def stopnode

    ec2 = Aws::EC2::Resource.new(region: params[:region])

    i = ec2.instance(params[:inst_id])

    inst = params[:inst_id]

    if i.exists?
      case i.state.code
        when 48  # terminated
          puts "#{inst} is terminated, can't be stopped"
        when 64  # stopping
          puts "#{inst} is stopping, please wait."
        when 89  # stopped
          puts "#{inst} is already stopped"
        else
          i.stop
      end
    end

    InfraUpdateWorker.perform_async

    redirect_to(infrastructure_index_path)
  end

  def startnode

    ec2 = Aws::EC2::Resource.new(region: params[:region])

    i = ec2.instance(params[:inst_id])

    inst = params[:inst_id]

    if i.exists?
      case i.state.code
        when 0  # pending
          puts "#{inst} is pending, so it will be running in a bit"
        when 16  # started
          puts "#{inst} is already started"
        when 48  # terminated
          puts "#{inst} is terminated, so you cannot start it"
        else
          i.start
      end
    end

    InfraUpdateWorker.perform_async

    redirect_to(infrastructure_index_path)
  end

  private

  def set_node
    @node = Node.find(params[:id])
  end

end

app/helpers/infrastructure_helper.rb
module InfrastructureHelper
end

app/views/infrastructure/index.html.haml
.row
  .col-md-4
    %h1.page-header Nodes at AWS
  .col-md-8
    = button_to 'Provision Instance', provision_node_path, remote: true, class: 'btn btn-primary top-btn', style: 'margin-left: 2em;'
    = button_to 'Sync with AWS', infra_sync_path, remote: true, class: 'btn btn-primary top-btn sync-btn'
  #progress-bar.col-md-12{style: 'display:none'}
    .progress
      #job-progress.progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "0",
      role: 'progressbar', style: 'width: 0%;'} 0%
%br
.row
  .col-lg-12
    - if @nodes.count <= 0
      .col-md-10.col-md-offset-1.well{style: 'text-align: center;'}
        %h3 No nodes on AWS

    - else
      - @nodes.each do |n|
        .col-md-3{style: 'margin-bottom: 3em;'}
          - if n.state == 'running'
            %i.fa.fa-server{style: 'font-size: 6em; margin-left: 30px; margin-bottom: 10px; color: #5cb85c;'}
          - elsif n.state == 'stopped'
            %i.fa.fa-server{style: 'font-size: 6em; margin-left: 30px; margin-bottom: 10px; color: #f0ad4e;'}
          - else
            %i.fa.fa-server{style: 'font-size: 6em; margin-left: 30px; margin-bottom: 10px; color: #d3d3d3;'}
          %br
          .caption
            %h4= 'EC2 ID: ' + n.aws_id
            - if n.aws_tags.count > 0
              - n.aws_tags.each_with_index do |t, i|
                %h5= t[0] + ': ' + t[1]
            - else
              %h5 Environment:
              %h5 Name:
            - if n.state == 'running'
              - if @debug
                = link_to node_destroy_path(n.id), class: 'btn btn-danger', style: 'margin-top: 1em;', method: :delete, data: { confirm: 'Are you sure?' } do
                  %i.fa.fa-trash{type: 'button', style: 'margin-top: 2.5px; font-size: 1.1em;'}
              = link_to infrastructure_path(n.id), class: 'btn btn-success', style: 'width: 130px; margin-top: 1em;' do
                %span{style: 'margin-right: 2em;'}= n.state.capitalize
                %i.fa.fa-chevron-right{type: 'button', style: 'float: right; margin-top: 2.5px;'}
            - elsif n.state == 'stopped'
              - if @debug
                = link_to node_destroy_path(n.id), class: 'btn btn-danger', style: 'margin-top: 1em;', method: :delete, data: { confirm: 'Are you sure?' } do
                  %i.fa.fa-trash{type: 'button', style: 'margin-top: 2.5px; font-size: 1.1em;'}
              = link_to infrastructure_path(n.id), class: 'btn btn-warning', style: 'width: 160px; margin-top: 1em;' do
                %span{style: 'margin-right: 2em;'}= n.state.capitalize
                %i.fa.fa-chevron-right{type: 'button', style: 'float: right; margin-top: 2.5px;'}
            - else
              - if @debug
                = link_to node_destroy_path(n.id), class: 'btn btn-danger', style: 'margin-top: 1em;', method: :delete, data: { confirm: 'Are you sure?' } do
                  %i.fa.fa-trash{type: 'button', style: 'margin-top: 2.5px; font-size: 1.1em;'}
              = link_to infrastructure_path(n.id), class: 'btn btn-default', style: 'width: 160px; margin-top: 1em;' do
                %span{style: 'margin-right: 2em;'}= n.state.capitalize
                %i.fa.fa-chevron-right{type: 'button', style: 'float: right; margin-top: 2.5px;'}
- if @debug
  %br
  .well{style: 'text-align: center;'}
    %h3 Only remove when instances have been removed from AWS
%hr
= link_to 'AWS Regions', aws_regions_path, class: 'btn btn-primary'

#job-id-container
  %p#job_id.hidden

%br
%br

app/views/infrastructure/infra_sync.js.erb
$('#job-id-container #job_id').text("<%= @job_id %>");
$('#progress-bar').show();

app/views/infrastructure/show.html.haml
.row
  .col-lg-5

    -if @staging
      %h1.page-header= 'Node ' + @node.aws_id
      %h3= 'State: ' + @node.state
    - elsif @node.state == 'running'
      %h1.page-header{style: 'color: #5cb85c;'}= 'Node ' + @node.aws_id + '    (' + @node.state + ')'
      = link_to 'Stop Instance', stop_node_path(region: @node.region, inst_id: @node.aws_id),
      class: 'btn btn-warning', method: :post
    - elsif @node.state == 'stopped'
      %h1.page-header{style: 'color: #f0ad4e;'}= 'Node ' + @node.aws_id + '    (' + @node.state + ')'
      = link_to 'Start Instance', start_node_path(region: @node.region, inst_id: @node.aws_id), class: 'btn btn-success',
      style: 'margin-right: 2em;', method: :post
      = link_to 'Terminate Instance', terminate_node_path(inst_id: @node.aws_id), class: 'btn btn-danger',
      style: 'margin-right: 2em;', method: :post
    - elsif @node.state == 'terminated'
      %h1.page-header{style: 'color: #d3d3d3;'}= 'Node ' + @node.aws_id + '    (' + @node.state + ')'
    - else
      %h1.page-header{style: 'color: #d3d3d3;'}= 'Node ' + @node.aws_id + '    (' + @node.state + ')'
      = link_to 'Stop Instance', stop_node_path(region: @node.region, inst_id: @node.aws_id), class: 'btn btn-warning'
      = link_to 'Start Instance', start_node_path(region: @node.region, inst_id: @node.aws_id), class: 'btn btn-success'
      = link_to 'Terminate Instance', terminate_node_path(inst_id: @node.aws_id), class: 'btn btn-danger',
      style: 'margin-right: 2em;', method: :post
    %br
    %br
    - @node.aws_tags.each_with_index do |n, i|
      %h5= n[0] + ': ' + n[1]
  .col-md-7
    = link_to 'Back', infrastructure_index_path, class: 'btn btn-default top-btn'

-if !@staging
  %br
  .row
    .col-lg-12
      %h2.page-header Emulators
      - if @node.account_sheets.count > 0
        %br
        %br
        .row
          - @node.account_sheets.order(:id).each do |a|
            .col-md-2.mobile-container
              - if a.status == 'taken'
                =link_to show_account_sheets_path(a.id) do
                  %i.fa.fa-mobile.mobile-icon.taken
                %br
                .caption
                  %h5= 'Status: ' + a.status.capitalize
                  %h5= 'PIN: ' + a.pin.to_s
                  %h5= 'ID: ' + a.id.to_s
              - elsif a.status== 'assigned'
                =link_to show_account_sheets_path(a.id) do
                  %i.fa.fa-mobile.mobile-icon.assigned
                %br
                .caption
                  %h5= 'Status: ' + a.status.capitalize
                  %h5= 'PIN: ' + a.pin.to_s
                  %h5= 'ID: ' + a.id.to_s
              - elsif a.status == 'removed'
                =link_to show_account_sheets_path(a.id) do
                  %i.fa.fa-mobile.mobile-icon.removed
                %br
                .caption
                  %h5= 'Status: ' + a.status.capitalize
                  %h5= 'PIN: ' + a.pin.to_s
                  %h5= 'ID: ' + a.id.to_s
              - elsif a.status == 'running'
                =link_to show_account_sheets_path(a.id) do
                  %i.fa.fa-mobile.mobile-icon.running
                %br
                .caption
                  %h5= 'Status: ' + a.status.capitalize
                  %h5= 'PIN: ' + a.pin.to_s
                  %h5= 'ID: ' + a.id.to_s
              - elsif a.status == 'none'
                =link_to show_account_sheets_path(a.id) do
                  %i.fa.fa-mobile.mobile-icon.none
                %br
                .caption
                  %h5= 'Status: ' + a.status.capitalize
                  %h5= 'PIN: ' + a.pin.to_s
                  %h5= 'ID: ' + a.id.to_s
              - else
                =link_to show_account_sheets_path(a.id) do
                  %i.fa.fa-mobile.mobile-icon.unknown
                %br
                .caption
                  %h5= 'Status: ' + a.status.capitalize
                  %h5= 'PIN: ' + a.pin.to_s
                  %h5= 'ID: ' + a.id.to_s
      - else
        .col-md-10.col-md-offset-1.well{style: 'text-align: center;'}
          %h3 No emulators
%br
.row
  .col-lg-12
    %h2.page-header Node Specs
    %table.table.table-striped
      %thead
        %tr
          %th Attribute
          %th Value

      %tbody
        %tr
          %td Hostname
          %td= @node.hostname
        %tr
          %td Region
          %td= @node.region
        %tr
          %td Architecture
          %td= @node.architecture
        %tr
          %td Hypervisor
          %td= @node.hypervisor
        %tr
          %td Instance Type
          %td= @node.instance_type
        %tr
          %td SSH Key Name
          %td= @node.key_name
        %tr
          %td Launched at
          %td= @node.launch_time
        %tr
          %td Availability Zone
          %td= @node.placement
        %tr
          %td Private DNS
          %td= @node.private_dns
        %tr
          %td Private IP
          %td= @node.private_ip
        %tr
          %td Public DNS
          %td= @node.public_dns
        %tr
          %td Public IP
          %td= @node.public_ip
        %tr
          %td Root Device Type
          %td= @node.root_device_type
        %tr
          %td Root Device Name
          %td= @node.root_device_name
        %tr
          %td Security Groups
          %td= @node.security_group
        %tr
          %td Reason for Current State
          %td= @node.state_reason
        %tr
          %td Reason for State Transition
          %td= @node.state_transition_reason
        %tr
          %td Subnet ID
          %td= @node.subnet_id
        %tr
          %td AWS Tags
          %td= @node.aws_tags
        %tr
          %td Virtualization Type
          %td= @node.virtualization_type
        %tr
          %td VPC ID
          %td= @node.vpc_id
        %tr
          %td Created
          %td= @node.created_at
        %tr
          %td Last Update
          %td= @node.updated_at